apiVersion: apps/v1
kind: Deployment
metadata:
  name: v2ray
spec:
  replicas: 1
  selector:
    matchLabels:
      app: v2ray
  template:
    metadata:
      labels:
        app: v2ray
    spec:
      containers:
      - image: okteto.dev/ray:latest
        name: v2ray
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/Tuxedo-html.zip"
        - name: Vless_UUID
          value: "dfba0b83-01b2-4029-9983-cf8fd9768020"
        - name: Vless_Path
          value: "/-vless"
        - name: Vmess_UUID
          value: "dfba0b83-01b2-4029-9983-cf8fd9768020"
        - name: Vmess_Path
          value: "/vmess"
        - name: Share_Path
          value: "/crtbnmiirtr"
